---
DOWN: 
  drop_table: 
    - categories
    - elements
    - elements_pages
    - groups
    - html_elements
    - news
    - pages
    - schema_info
    - text_elements
    - users
UP: 
  create_table: 
    categories: 
      name: 
        type: string
        default: false
        length: 50
        - not_null
      slug: 
        type: string
        default: false
        length: 50
        - not_null
      sort: 
        type: integer
        default: false
        length: 11
        - not_null
    elements: 
      name: 
        type: string
        default: false
        length: 64
        - not_null
      description: 
        type: string
        default: false
        length: 
        - not_null
      class: 
        type: string
        default: false
        length: 128
        - not_null
      - no_dates
    elements_pages: 
      element_id: 
        type: integer
        default: false
        length: 11
        - not_null
      page_id: 
        type: integer
        default: false
        length: 11
        - not_null
      container: 
        type: string
        default: false
        length: 64
        - not_null
      foreign_id: 
        type: integer
        default: false
        length: 11
        - not_null
      - no_dates
    groups: 
      name: 
        type: string
        default: false
        length: 50
        - not_null
      access: 
        type: string
        default: false
        length: 20
        - not_null
      - no_dates
    html_elements: 
      element_id: 
        type: integer
        default: false
        length: 11
        - not_null
      value: 
        type: text
        default: false
        length: 
        - not_null
      - no_dates
    news: 
      title: 
        type: string
        default: false
        length: 255
        - not_null
      content: 
        type: text
        default: false
        length: 
        - not_null
      slug: 
        type: string
        default: false
        length: 255
        - not_null
      draft: 
        type: boolean
        default: false
        length: 1
        - not_null
    pages: 
      title: 
        type: string
        default: false
        length: 120
        - not_null
      content: 
        type: text
        default: false
        length: 
        - not_null
      slug: 
        type: string
        default: false
        length: 255
        - not_null
      meta_keywords: 
        type: string
        default: false
        length: 255
        - not_null
      meta_description: 
        type: string
        default: false
        length: 255
        - not_null
      tags: 
        type: string
        default: false
        length: 255
        - not_null
      parent_id: 
        type: integer
        default: false
        length: 10
        - is_null
      lft: 
        type: integer
        default: false
        length: 10
        - not_null
      rght: 
        type: integer
        default: false
        length: 10
        - not_null
      draft: 
        type: boolean
        default: false
        length: 1
        - not_null
    schema_info: 
      version: 
        type: integer
        default: false
        length: 3
        - is_null
      - no_id
      - no_dates
    text_elements: 
      element_id: 
        type: integer
        default: false
        length: 11
        - not_null
      value: 
        type: text
        default: false
        length: 
        - not_null
      - no_dates
    users: 
      group_id: 
        type: integer
        default: false
        length: 11
        - not_null
      username: 
        type: string
        default: false
        length: 50
        - not_null
      password: 
        type: string
        default: false
        length: 40
        - not_null
      name: 
        type: string
        default: false
        length: 50
        - not_null
      email: 
        type: string
        default: false
        length: 30
        - not_null
